name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      ADMIN_PASSWORD_HASH: 'de8e5a02ad7b5549566958de1b86c612f2403c78add37349345b0e8d2b0b6fb8'
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      TINYMCE_API_KEY: ${{ secrets.TINYMCE_API_KEY }}
      NODE_ENV: test
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci

    - name: Create config.js for tests
      run: |
        echo "window.config = {" > config.js
        echo "  ADMIN_PASSWORD_HASH: '$ADMIN_PASSWORD_HASH'" >> config.js
        echo "};" >> config.js

    - name: Replace TinyMCE API Key for tests
      run: sed -i "s/TINYMCE_API_KEY_PLACEHOLDER/${{ secrets.TINYMCE_API_KEY }}/g" admin.html
    
    - name: Install Playwright browsers (Chromium only)
      run: npx playwright install --with-deps chromium
    
    - name: Run Playwright tests
      run: npx playwright test --project=chromium
    
    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7